#!/bin/sh
#
# Disable Bluetooth SSP mode at boot
#

HCI_DEV="hci0"

start() {
    echo "Disabling Bluetooth SSP on $HCI_DEV..."

    # Attendre que l'interface existe
    for i in $(seq 1 10); do
        hciconfig $HCI_DEV >/dev/null 2>&1 && break
        sleep 1
    done

    # Interface up (au cas où)
    hciconfig $HCI_DEV up

    # Désactiver SSP
    hciconfig $HCI_DEV sspmode 0
}

stop() {
    :
}

case "$1" in
    start)
        start
        ;;
    *)
        exit 0
        ;;
esac

